name: ShellCheck

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@1.1.0
      with:
        check_together: 'yes'
        severity: error
